{
 "title": "WPF 07",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Taktung",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM (\n  SELECT\n    $__timeGroup(timestamp,$__interval)\n  FROM sepicker\n  WHERE\n    $__timeFilter(timestamp) AND\n    name = 'WP_PUMPENSTATUS' AND\n    value = '1'\n  GROUP BY 1\n) AS entries"
    }
   ]
  },
  {
   "title": "Fehler",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMESTAMP) AS time_sec,\n  0 + value AS value,\n  name AS metric\nFROM sepicker\nWHERE\n  name = 'FEHLER' AND\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Übersicht",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMESTAMP) AS time_sec,\n  0 + value AS value,\n  name AS metric\nFROM sepicker\nWHERE\n  name IN('ISTTEMPERATUR_HK_1', 'SOLLTEMPERATUR_HK_1', 'ISTTEMPERATUR_HK_2', 'SOLLTEMPERATUR_HK_2', 'AUSSENTEMPERATUR', 'VORLAUFISTTEMPERATUR_WP', 'VORLAUFISTTEMPERATUR_NHZ', 'RÜCKLAUFISTTEMPERATUR', 'PUFFERISTTEMPERATUR', 'PUFFERSOLLTEMPERATUR', 'WARMWASSER_ISTTEMPERATUR', 'WARMWASSER_SOLLTEMPERATUR', 'QUELLENTEMPERATUR', 'WP_PUMPENSTATUS') AND\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Spreizung WP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMESTAMP) AS time_sec,\n  0 + value AS value,\n  name AS metric\nFROM sepicker\nWHERE\n  name IN('VORLAUFISTTEMPERATUR_WP', 'RÜCKLAUFISTTEMPERATUR') AND\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Warmwasser",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMESTAMP) AS time_sec,\n  0 + value AS value,\n  name AS metric\nFROM sepicker\nWHERE\n  name IN('WARMWASSER_ISTTEMPERATUR', 'WARMWASSER_SOLLTEMPERATUR') AND\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Puffer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMESTAMP) AS time_sec,\n  0 + value AS value,\n  name AS metric\nFROM sepicker\nWHERE\n  name IN('PUFFERISTTEMPERATUR', 'PUFFERSOLLTEMPERATUR') AND\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Quelle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMESTAMP) AS time_sec,\n  0 + value AS value,\n  name AS metric\nFROM sepicker\nWHERE\n  name IN(\"QUELLENTEMPERATUR\", \"AUSSENTEMPERATUR\") AND\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Fußbodenheizung",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMESTAMP) AS time_sec,\n  0 + value AS value,\n  name AS metric\nFROM sepicker\nWHERE\n  name IN('ISTTEMPERATUR_HK_2', 'SOLLTEMPERATUR_HK_2') AND\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Pumpenstatus WP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMESTAMP) AS time_sec,\n  0 + value AS value,\n  name AS metric\nFROM sepicker\nWHERE\n  name = \"WP_PUMPENSTATUS\" AND\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  }
 ]
}